// Shared death data used across pages
const DEATHS = [
  { rank:"01", name:"Heart disease",          icon:"♥",  odds:"1 in 6",           oddsLabel:"lifetime odds", pct:100, cat:"cat-chronic",  detail:"702,880 US deaths in 2022 (CDC)",                         annualUS:702880, globalAnnual:20500000 },
  { rank:"02", name:"Cancer",                  icon:"☢",  odds:"1 in 7",           oddsLabel:"lifetime odds", pct:92,  cat:"cat-chronic",  detail:"608,371 US deaths in 2022 (CDC)",                         annualUS:608371, globalAnnual:10000000 },
  { rank:"03", name:"COVID-19 / respiratory",  icon:"🫁", odds:"1 in 17",          oddsLabel:"lifetime odds", pct:60,  cat:"cat-epidemic", detail:"75,521 US deaths in 2023 (CDC, post-peak)",               annualUS:75521,  globalAnnual:2800000 },
  { rank:"04", name:"Accidental overdose",     icon:"💊", odds:"1 in 65",          oddsLabel:"lifetime odds", pct:50,  cat:"cat-accident", detail:"107,941 US deaths in 2022 (CDC WONDER)",                  annualUS:107941, globalAnnual:600000 },
  { rank:"05", name:"Car crash",               icon:"🚗", odds:"1 in 101",         oddsLabel:"lifetime odds", pct:45,  cat:"cat-accident", detail:"42,795 US deaths in 2022 (NHTSA)",                        annualUS:42795,  globalAnnual:1350000 },
  { rank:"06", name:"Fall",                    icon:"🪜", odds:"1 in 106",         oddsLabel:"lifetime odds", pct:44,  cat:"cat-accident", detail:"44,686 US deaths in 2022 (CDC)",                          annualUS:44686,  globalAnnual:684000 },
  { rank:"07", name:"Gun violence",            icon:"⚠",  odds:"1 in 179",         oddsLabel:"lifetime odds", pct:35,  cat:"cat-violence", detail:"48,204 US deaths in 2022 incl. suicide (CDC)",            annualUS:48204,  globalAnnual:250000 },
  { rank:"08", name:"Exercise cardiac arrest", icon:"🏃", odds:"1 in 50,000",      oddsLabel:"per marathon",  pct:22,  cat:"cat-accident", detail:"~7,000 US exercise cardiac arrests/year (AHA 2023)",      annualUS:7000,   globalAnnual:180000 },
  { rank:"09", name:"Drowning",                icon:"🌊", odds:"1 in 1,000",       oddsLabel:"lifetime odds", pct:20,  cat:"cat-accident", detail:"4,016 US deaths in 2022 (CDC)",                           annualUS:4016,   globalAnnual:236000 },
  { rank:"10", name:"Fire or smoke",           icon:"🔥", odds:"1 in 1,500",       oddsLabel:"lifetime odds", pct:15,  cat:"cat-accident", detail:"2,564 US deaths in 2022 (NFPA)",                          annualUS:2564,   globalAnnual:180000 },
  { rank:"11", name:"Vending machine tip-over",icon:"🍫", odds:"1 in 112 million", oddsLabel:"lifetime odds", pct:7,   cat:"cat-rare",     detail:"37 deaths over 17 years, US (CPSC historical)",           annualUS:2,      globalAnnual:5 },
  { rank:"12", name:"Lightning strike",        icon:"⚡", odds:"1 in 138,000",     oddsLabel:"lifetime odds", pct:5,   cat:"cat-rare",     detail:"~18–22 US deaths/year avg. (NOAA 2024)",                  annualUS:20,     globalAnnual:2000 },
  { rank:"13", name:"Plane crash",             icon:"✈",  odds:"1 in 205,000",     oddsLabel:"lifetime odds", pct:3,   cat:"cat-rare",     detail:"~350 US deaths/year avg. (NTSB 2023, all aviation)",      annualUS:350,    globalAnnual:600 },
  { rank:"14", name:"TV tip-over",             icon:"📺", odds:"1 in 400,000",     oddsLabel:"lifetime odds", pct:2.5, cat:"cat-rare",     detail:"~450 US deaths/year (CPSC 2022)",                         annualUS:450,    globalAnnual:1200 },
  { rank:"15", name:"Roller coaster (heart)",  icon:"🎢", odds:"1 in 750 million", oddsLabel:"per ride odds", pct:1.8, cat:"cat-absurd",   detail:"~4 US deaths/year avg. (IAAPA 2023)",                     annualUS:4,      globalAnnual:15 },
  { rank:"16", name:"Shark attack",            icon:"🦈", odds:"1 in 3.7 million", oddsLabel:"lifetime odds", pct:1.2, cat:"cat-absurd",   detail:"57 unprovoked attacks globally in 2022; 5 fatal (ISAF)", annualUS:1,      globalAnnual:5 },
  { rank:"17", name:"Fire ant anaphylaxis",    icon:"🐜", odds:"1 in 9 million",   oddsLabel:"lifetime odds", pct:1.0, cat:"cat-absurd",   detail:"30–90 US deaths/year from fire ant anaphylaxis (CDC)",   annualUS:60,     globalAnnual:200 },
  { rank:"18", name:"Laughing to death",       icon:"😂", odds:"1 in 50 million",  oddsLabel:"lifetime odds", pct:0.8, cat:"cat-absurd",   detail:"handful of confirmed cases globally, ever",               annualUS:0,      globalAnnual:1 },
  { rank:"19", name:"Gas ignition",            icon:"💨", odds:"1 in 100+ million",oddsLabel:"lifetime odds", pct:0.6, cat:"cat-absurd",   detail:"a handful of documented surgical cases globally",         annualUS:0,      globalAnnual:1 },
  { rank:"20", name:"Choking on own beard",    icon:"🧔", odds:"1 in ∞",           oddsLabel:"historical",    pct:0.4, cat:"cat-absurd",   detail:"documented once in recorded human history",               annualUS:0,      globalAnnual:0 },
];

const ABSURD = [
  { emoji:"😂", cause:"Laughing to death",      prob:"handful ever",                tag:"fatal gelastic syncope" },
  { emoji:"💨", cause:"Passing gas (ignited)",  prob:"documented surgical cases",   tag:"methane + laser = fire" },
  { emoji:"🏃", cause:"Marathon cardiac arrest",prob:"1 in 50,000 runners",         tag:"7,000 US/yr (AHA)" },
  { emoji:"🦈", cause:"Shark attack",           prob:"57 attacks in 2022; 5 fatal", tag:"ISAF global data" },
  { emoji:"🐜", cause:"Fire ant anaphylaxis",   prob:"30–90 US/yr",                 tag:"more than planes" },
  { emoji:"🐄", cause:"Cow attack",             prob:"~22 US/yr",                   tag:"25× more than sharks" },
  { emoji:"🎢", cause:"Roller coaster (heart)", prob:"~4 US/yr (IAAPA)",            tag:"too much fun" },
  { emoji:"🍫", cause:"Vending machine tip",    prob:"37 deaths, 1978–1995",        tag:"CPSC historical" },
  { emoji:"🐢", cause:"Falling turtle",         prob:"1 in ∞",                      tag:"aeschylus only" },
  { emoji:"🥥", cause:"Falling coconut",        prob:"~150/yr global",              tag:"look up more" },
  { emoji:"🤳", cause:"Selfie fall",            prob:"~379 deaths 2011–2017",       tag:"global estimate" },
  { emoji:"📺", cause:"TV tip-over",            prob:"~450 US/yr (CPSC)",           tag:"strap your tvs" },
  { emoji:"🎈", cause:"Helium asphyxiation",    prob:"~1–2/yr US",                  tag:"party gone wrong" },
  { emoji:"💇", cause:"Salon neck position",    prob:"rare but documented",          tag:"beauty stroke syndrome" },
  { emoji:"👖", cause:"Stuck in skinny jeans",  prob:"documented 2015",             tag:"squatting was a mistake" },
  { emoji:"📚", cause:"Book avalanche",         prob:"rare but real",               tag:"tsundoku kills" },
];
